# -*- coding: utf-8 -*-
"""tensorflow_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wL7TGSp2KqyxQ6PxeEvZS_RERleBDYIZ

安裝 TensorFlow, 2.0 無 tf.InteractiveSession()
"""

import tensorflow as tf

tf.version

tf.compat.v1.InteractiveSession()

"""zero 張量"""

tf.zeros(2)

a = tf.zeros(2)
a

a = tf.zeros((2,3))
a

"""將任意值(0,1以外)填入張量"""

b = tf.fill((2, 2), value=5)
b

"""建立常數張量"""

a = tf.constant(3)
a

"""隨機抽樣"""

a = tf.random.normal([2,2], 0, 1, tf.float32, seed=1)
a

a = tf.random.uniform((2,2), -10, 10)
a

"""張量相加、伸縮"""

c = tf.ones((2, 2))
d = tf.ones((2, 2))
e = c + d
e

f = 2 * e
f

"""非矩陣乘法是逐元素乘法"""

c = tf.fill((2, 2), 2)
d = tf.fill((2, 2), 7)
e = c * d
e

"""建立單位矩陣"""

a = tf.eye(4)
a

"""建立對角矩陣"""

r  = tf.range(1, 5, 1)
r

d = tf.linalg.diag(r)
d

a = tf.ones((2, 3))
a

"""矩陣轉置"""

at = tf.transpose(a)
at

"""矩陣乘法"""

a = tf.ones((2, 3))
b = tf.ones((3, 4))
c = tf.matmul(a, b)
c

"""張量型態"""

a = tf.ones((2, 2), dtype=tf.int32)
a

a = tf.ones((2, 2), dtype=tf.int64)
a

"""轉換函式"""

b = tf.compat.v1.to_float(a)
b

b = tf.cast(a, dtype=float)
b

"""改變張量形狀"""

a = tf.ones(8)
b = tf.reshape(a, (4, 2))
b

c = tf.reshape(a, (2, 2, 2))
c

"""取得形狀"""

a = tf.ones(2)
a.get_shape()

"""為張量多加一維度"""

b = tf.expand_dims(a, 0)
b.get_shape()

b

c = tf.expand_dims(a, 1)
c.get_shape()

c

"""張量的維度移除1"""

d = tf.squeeze(b)
d.get_shape()

d

"""broadcasting: 不同尺寸的矩陣和向量可以相加"""

a = tf.ones((2,2))
a

b = tf.range(0, 2, 1)
b

"""型態不會自動轉換"""

c = a + b

b = tf.range(0, 2, 1, dtype=float)
b

c = a + b
c

"""當沒有明確指定tf.graph時，TensorFlow會隱藏的實例中加入張亮與運算，可用tf.Graph()取得實例"""

tf.Graph()

"""tf.Variable()類別可包裝張量來執行有狀態的計算。variable物件是張量的容器"""

a = tf.Variable(tf.ones((2, 2)))
a

a.assign((tf.zeros((2, 2))))

a

"""形狀不同時會失敗"""

a.assign((tf.zeros((2, 3))))

